version: "3.3"
services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
  web:
    container_name: order-app
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/order_app
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
